version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - go build -o bin/gobank
  
  run: 
    cmds:
      - task: build
      - ./bin/gobank
  
  test:
    cmds:
      - task: build
      - go test -v ./...
